/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applicationFrames;

import databaseConnection.DatabaseConnection;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Anta
 */
public class EmpSingUp extends javax.swing.JFrame {

    /**
     * Creates new form SingUpFrame
     */
    public EmpSingUp() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
//        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnSingInNow = new javax.swing.JButton();
        jBtnCreateAcc = new javax.swing.JButton();
        lblCreateUsername = new javax.swing.JLabel();
        lblCreatePassword = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCreateUsername = new javax.swing.JTextField();
        txtCreatePassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        txtUserErr = new javax.swing.JLabel();
        txtPassErr = new javax.swing.JLabel();
        jTextID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabelEmptyID = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(95, 95, 161));

        jBtnSingInNow.setText("Sing In");
        jBtnSingInNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSingInNowActionPerformed(evt);
            }
        });

        jBtnCreateAcc.setText("Create Account");
        jBtnCreateAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCreateAccActionPerformed(evt);
            }
        });

        lblCreateUsername.setText("Create Username :");

        lblCreatePassword.setText("Create Password :");

        jLabel3.setText("Already have an account?");

        txtCreateUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCreateUsernameKeyReleased(evt);
            }
        });

        txtCreatePassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCreatePasswordKeyReleased(evt);
            }
        });

        jLabel1.setText("Create your account :");

        txtUserErr.setForeground(new java.awt.Color(255, 0, 0));

        txtPassErr.setForeground(new java.awt.Color(255, 0, 0));
        txtPassErr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassErrKeyPressed(evt);
            }
        });

        jLabel2.setText("Enter your ID :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelEmptyID, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCreatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCreateUsername))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextID, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(txtUserErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPassErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCreateUsername)
                            .addComponent(txtCreatePassword)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jBtnSingInNow, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBtnCreateAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(169, 169, 169))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabelEmptyID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreateUsername)
                    .addComponent(txtCreateUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(txtUserErr, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCreatePassword)
                    .addComponent(txtCreatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtPassErr, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnCreateAcc)
                .addGap(32, 32, 32)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnSingInNow)
                .addGap(75, 75, 75))
        );

        jPanel2.setBackground(new java.awt.Color(56, 56, 110));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/zaposleni2.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/samoLogo1.png"))); // NOI18N
        jLabel6.setText("LOGO APLIKACIJE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSingInNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSingInNowActionPerformed
                EmpLogin ligi = new EmpLogin();
                ligi.setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_jBtnSingInNowActionPerformed

    private void jBtnCreateAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCreateAccActionPerformed
     
        if(txtCreateUsername.getText().trim().isEmpty() && txtCreatePassword.getText().trim().isEmpty() && jTextID.getText().isEmpty()){
            txtUserErr.setText("Username is Empty");
            txtPassErr.setText("Password is Empty");
            jLabelEmptyID.setText("You must enter your ID");
            return;
        }else if(txtCreateUsername.getText().trim().isEmpty()){
            txtUserErr.setText("Username is Empty");
            return;
        }else if(txtCreatePassword.getText().trim().isEmpty()){
            txtPassErr.setText("Password is Empty");
            return;
        }else if(jTextID.getText().isEmpty()){
            jLabelEmptyID.setText("You must enter your ID");
            return;
        }
       
        //PROVERA DA LI ID postoji u zaposlenitable a ako postoji proverava se da li je iskoriscen
        if(!proveraIDuZap()){
            JOptionPane.showMessageDialog(null, "Vas ID ne postoji");
            return;
        }
        if(proveraIDuLog()){
            JOptionPane.showMessageDialog(null, "Vas ID je vec iskoriscen");
            return;
        }
        char[] chars = txtCreatePassword.getPassword();

        boolean contains = false;
        for (char c : chars) {
//                if (c == '1' || c == '2'|| c =='3'|| c =='4'|| c =='5'|| c =='6'|| c =='7'|| c =='8'|| c =='9'|| c =='0') {
              if(Character.isDigit(c)){
                contains = true;
                continue;
            }
        }
        if(!contains){
            JOptionPane.showMessageDialog(null, "Password must contain at least one number");
            txtCreatePassword.setText("");
            return;
        }    
        if(txtCreatePassword.getText().toString().length() > 6 && !proveraUser()){
//        if(proveraUser()){
//            return;
//        }
//        if(!proveraAcc()){
//            return;
//        }
        try{
            //Pravljenje novog acc
            String query = "INSERT INTO logintable(id,username,password)VALUES(?,?,?)";
            PreparedStatement pst = DatabaseConnection.getConnection().prepareStatement(query);
            int id  = Integer.parseInt(jTextID.getText());
            pst.setInt(1, id);
            pst.setString(2,txtCreateUsername.getText());

//          pst.setString(3,txtCreatePassword.getText()); STARI NACIN JOS IZ JAVA 2
//          NOVI NACIN JE PREKO METODE getPassword koja vraca charArray
            String pass = new String(txtCreatePassword.getPassword());
            pst.setString(3,pass);

            JOptionPane.showMessageDialog(null, "You created your acc Sucessfully");
            pst.executeUpdate();
            
        }catch(Exception e){
            System.out.println("Problem je u unosu"); 
            JOptionPane.showMessageDialog(null,e);
            }  
        }
    }//GEN-LAST:event_jBtnCreateAccActionPerformed

    private void txtCreateUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCreateUsernameKeyReleased
        if(proveraUser()){
            txtUserErr.setText("This usrename alredy exist");
        }else{
            txtUserErr.setText("");
        }
    }//GEN-LAST:event_txtCreateUsernameKeyReleased

    private void txtPassErrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassErrKeyPressed
        //
    }//GEN-LAST:event_txtPassErrKeyPressed

    private void txtCreatePasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCreatePasswordKeyReleased
        if(txtCreatePassword.getText().toString().length() == 0 || txtCreatePassword.getText().toString().length() > 6){
            txtPassErr.setText("");
            return;
        }
        txtPassErr.setText("Password is too short");
    }//GEN-LAST:event_txtCreatePasswordKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCreateAcc;
    private javax.swing.JButton jBtnSingInNow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelEmptyID;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextID;
    private javax.swing.JLabel lblCreatePassword;
    private javax.swing.JLabel lblCreateUsername;
    private javax.swing.JPasswordField txtCreatePassword;
    private javax.swing.JTextField txtCreateUsername;
    private javax.swing.JLabel txtPassErr;
    private javax.swing.JLabel txtUserErr;
    // End of variables declaration//GEN-END:variables

//    private boolean proveraAcc() {
//        try{
//        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javabazeapp", "root","");
//         
//        String sql = "SELECT * FROM logintable WHERE username = ? AND password = ?";
//         
//        PreparedStatement pst = con.prepareStatement(sql);
//        pst.setString(1, txtCreateUsername.getText());
//        pst.setString(2, txtCreatePassword.getText());
//        
//        ResultSet rs = pst.executeQuery();
//            if(rs.next()){
//                JOptionPane.showMessageDialog(null, "Account already exist");
//                txtCreateUsername.setText("");
//                txtCreatePassword.setText("");
//                return false;
//            }  
//
//        }catch(Exception e){
//            JOptionPane.showMessageDialog(null,e);
//        } 
//        return true;
//    }

    private boolean proveraUser() {
        try{
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javabazeapp", "root","");
         
        String sql = "SELECT * FROM logintable WHERE username = ?";
         
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, txtCreateUsername.getText());
        
        ResultSet rs = pst.executeQuery();
            if(rs.next()){
                return true;
            }  

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        } 
        return false;
    }    

    private boolean proveraIDuLog() {
        try{
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javabazeapp", "root","");
        
        String sql = "SELECT * FROM logintable WHERE id = ?";
        
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, jTextID.getText());
        
        ResultSet rs = pst.executeQuery();
        
            if(rs.next()){
                jTextID.setText("");
                return true;
            }
            }catch(Exception e){
            System.out.println("proveraIDuLog greska");
            JOptionPane.showMessageDialog(null,e);
        }  
        return false;
    }

    private boolean proveraIDuZap() {
        try{
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javabazeapp", "root","");
        
        String sql = "SELECT * FROM zaposlenitable WHERE id = ?";
        
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, jTextID.getText());
        
        ResultSet rs = pst.executeQuery();
            if(rs.next()){
                return true;
            }
            
            }catch(Exception e){
            System.out.println("Greska u proveraIDuZap");
            JOptionPane.showMessageDialog(null,e);
        } 
        jTextID.setText("");
        return false;
    }  
}
